# Generated by Django 5.2.5 on 2025-08-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDistribucion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventOffset',
            fields=[
                ('event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('chofer_nombre', models.CharField(max_length=200)),
                ('total_ordenes', models.PositiveIntegerField(default=0)),
                ('estado_completitud', models.CharField(choices=[('INC', 'Incompleto'), ('COM', 'Completo')], db_index=True, default='INC', max_length=3)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques', to='distribucion.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pyme_id', models.CharField(db_index=True, max_length=64)),
                ('origen_cd_id', models.CharField(db_index=True, max_length=64)),
                ('destino_cd_id', models.CharField(db_index=True, max_length=64)),
                ('fecha_despacho', models.DateTimeField(db_index=True)),
                ('estado_preparacion', models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completa')], db_index=True, default='PEN', max_length=3)),
                ('peso_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volumen_total', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='distribucion.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('ENT', 'Entregada'), ('REJ', 'Rechazada')], db_index=True, max_length=3)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribucion.chofer')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion', to='distribucion.orden')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloque_ordenes', to='distribucion.bloque')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_bloques', to='distribucion.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('qty', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volumen', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='distribucion.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cd_id', models.CharField(db_index=True, max_length=64)),
                ('fecha_recepcion', models.DateTimeField(db_index=True)),
                ('usuario_receptor', models.CharField(max_length=120)),
                ('incidencias', models.BooleanField(default=False)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='distribucion.orden')),
            ],
        ),
        migrations.AddIndex(
            model_name='bloque',
            index=models.Index(fields=['fecha'], name='distribucio_fecha_1743a4_idx'),
        ),
        migrations.AddIndex(
            model_name='bloque',
            index=models.Index(fields=['chofer', 'estado_completitud'], name='distribucio_chofer__d00858_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['pyme_id', 'fecha_despacho'], name='distribucio_pyme_id_38e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['destino_cd_id', 'fecha_despacho'], name='distribucio_destino_2efa55_idx'),
        ),
        migrations.AddIndex(
            model_name='distribucion',
            index=models.Index(fields=['estado', 'fecha_entrega'], name='distribucio_estado_71af71_idx'),
        ),
        migrations.AddIndex(
            model_name='distribucion',
            index=models.Index(fields=['chofer', 'estado'], name='distribucio_chofer__8cd3fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bloqueorden',
            unique_together={('bloque', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='ordenproducto',
            unique_together={('orden', 'sku')},
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['cd_id', 'fecha_recepcion', 'incidencias'], name='distribucio_cd_id_bd1fee_idx'),
        ),
    ]
