# Generated by Django 5.2.5 on 2025-08-15 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('peso', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volumen', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('preparada', models.BooleanField(default=False)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_preparador', models.CharField(blank=True, max_length=120, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='distribucion.orden')),
            ],
            options={
                'indexes': [models.Index(fields=['orden'], name='distribucio_orden_i_a6dabb_idx')],
            },
        ),
    ]
