# Generated by Django 5.2.5 on 2025-08-16 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0002_bolsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='pyme_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribucion.pyme'),
        ),
        migrations.AddField(
            model_name='pyme',
            name='tipo',
            field=models.CharField(choices=[('CD', 'Centro de Distribución'), ('CAP', 'Centro de Admisión')], default='CD', max_length=3),
        ),
    ]
