FROM node:22-alpine

WORKDIR /app

ENV NG_CLI_ANALYTICS=ci \
    CHOKIDAR_USEPOLLING=1 \
    CHOKIDAR_INTERVAL=200 \
    NODE_ENV=development \
    PORT=4200 \
    CHROME_BIN=/usr/bin/chromium-browser \
    MODE=serve

RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ttf-freefont \
      ca-certificates

# Dependencias
COPY package*.json ./
RUN npm ci

# Código
COPY . .

EXPOSE 4200


CMD ["sh", "-lc", "\
  case \"$MODE\" in \
    test)        npx ng test --browsers=ChromeHeadlessNoSandbox --watch=false --code-coverage ;; \
    test:watch)  npx ng test --browsers=ChromeHeadlessNoSandbox ;; \
    *)           npx ng serve --host 0.0.0.0 --port ${PORT} --proxy-config proxy.conf.json ;; \
  esac \
"]
